services:
  postgres:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mateo2020
      POSTGRES_DB: training-back-db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    command: npm run start:dev
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:mateo2020@postgres:5432/training-back-db"

volumes:
  postgres_data:
